### ISSUE TITLE
molecule: platforms missing networks dictionary (docker/podman)

### ISSUE THREAD

**Issue by ThomasSanson** [ansible/schemas#167]
Hi,

Molecule schema is missing `networks` into `platforms`.

```yaml
platforms:
  - name: test
    networks:
      - name: test
 ```

See https://github.com/ansible-community/molecule/blob/main/src/molecule/model/schema_v3.py#L288

Thank you
