### ISSUE TITLE
Molecule schema: Missing properties children for platforms

### ISSUE THREAD

**Issue by ThomasSanson** [ansible/schemas#168]
Hi,

Molecule schema is missing `children` into `platforms`.

```yaml
platforms:
  - name: test
    groups: [applications]
    children: [app1]
 ```

See https://github.com/ansible-community/molecule/blob/main/src/molecule/model/schema_v3.py#L148

Thank you
