### ISSUE TITLE
Role dependencies don't support `become` and `when` properties

### ISSUE THREAD

**Issue by nre-ableton** [ansible/schemas#277]
Although it's not well-documented, these properties do work in an Ansible role `meta/main.yml` file. Example:

```yaml
---
galaxy_info:
  description: foo
  license: MIT
  min_ansible_version: "2.10"
  platforms: []

dependencies:
  - role: foo_with_condition
    when: inventory_hostname == "foo"
  - role: bar_become
    become: true
```
