### ISSUE TITLE
Meta schema: Missing properties namespace for galaxy_info

### ISSUE THREAD

**Issue by ThomasSanson** [ansible/schemas#287]
Hi,

Meta schema is missing properties namespace into meta for galaxy_info

```yaml
---
galaxy_info:
  author: Thomas Sanson
  company: XXX
  description: Installation d'XXX pour RHEL
  namespace: my_namespace
  role_name: xxx
```

```bash
WARNING  Listing 1 violation(s) that are fatal
meta/main.yml:1: schema: Additional properties are not allowed ('namespace' was unexpected) (schema[meta])
You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - experimental  # all rules tagged as experimental
```

Like role_name, see : https://github.com/ansible/schemas/blob/main/f/ansible-meta.json#L572

Thank you
