### ISSUE TITLE
requirements.yml with roles and collections sections complains about "include" entries for roles

### ISSUE THREAD

**Issue by frittentheke** [ansible/schemas#296]
When placing collections and roles in a `requirements.yml` file, like:

```
---
collections:
- name: ansible.posix
  version: ">=1.2.0"
- name: community.general
  version: ">=3.4.0"

roles:
- include: some-more-requirements.yml
```

ansible-lint complains about the included role `- include: some-more-requirements.yml` with:
 `Property include is not allowed.yaml-schema: Role
`

First of all this code actually works (included roles are checked and installed by ansible-galaxy on `install -r requirements.yml`).
But also reading https://galaxy.ansible.com/docs/using/installing.html#multiple-roles-from-multiple-files and https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file clearly advertises to use a combined file for `collections` and `roles`.
