### ISSUE TITLE
"Additional properties are not allowed" in meta schema but probably should be

### ISSUE THREAD

**Issue by kalibyrn** [ansible/schemas#309]
I had just started using ansible-lint and fixed up my code to conform to the rules that ansible-lint provides. However, I ran across an issue that could probably be adjusted. You can read more about how I found it here: https://github.com/ansible/ansible/issues/78019

My `meta/main.yml` files originally looked something like this:
```
---
dependencies:
  - role: example_role
  - role: example_role
    example_var: example_value
```
ansible-lint gave me this error with this code:
```
schema: Additional properties are not allowed ('example_var' was unexpected) (schema[meta])
```
So, I changed the code to look more like this:
```
---
dependencies:
  - role: example_role
  - role: example_role
    vars:
      example_var: example_value
```
However, that caused all sorts of problems in my plays and roles because `vars` is scoped at the play level and is pre-processed, meaning that if I call a role without the variable defined in the _first_ call, **it will be defined anyway due to it being specified in the _second_ call**. 

The recommended course of action was to use "role params" instead, which is what I had originally been doing. I'm not really knowledgeable enough about schemas and was hoping that if someone had the time, if they would be able to account for this behavior by changing the schema to allow additional properties.

I'm also not sure if another issue could spawn out of this or not: The "vars" behavior is really strange when you don't understand why it's happening. Having the linter catch conditions where `vars` is set in multiple places with conflicting values may help catch unexpected behavior. 

The output of `ansible-lint --version` is:
```
ansible-lint 6.3.0 using ansible 2.12.6
```

**Comment by ssbarnea** [comment]
@kalibyrn I don't know where you got first example from because I doubt Ansible ever allowed you to add variables at the root of role object inside dependencies. AFAIK, you must use `vars:` for var.

I am inclined be strongly against setting `additionalProperties=true` there as that would prevent us from catching at least 50% of errors, like typos.

additionalProperties=false is the secret sauce for detecting typos but we cannot always use it.

@s-hertel WDYT?

**Comment by kalibyrn** [comment]
Hi @ssbarnea thanks for your reply. Ansible certainly seems to allow variables at the root of the role object inside the dependencies block. Whether it should or not, I can't comment on. I've attached a tar.gz file with sample files that might demonstrate the issue better.

In the first role's meta/main.yml file (the role is called "meta_test_vars") we have:

```
---
dependencies:
  - role: debug_test
    vars:
      iteration: 1
  - role: debug_test
    vars:
      iteration: 2
      passed_value: 'should be passed in iteration 2'
  - role: debug_test
    vars:
      iteration: 3
      passed_value: 'should be passed in iteration 3'
  - role: debug_test
    vars:
      iteration: 4
```
and we get the following (somewhat confusing) values for `passed_value`:

1. expected: `undefined`, actual: "should be passed in iteration 3"
2. expected: "should be passed in iteration 2", actual: "should be passed in iteration 2"
3. expected: "should be passed in iteration 3", actual: "should be passed in iteration 3"
4. expected: `undefined`, actual: "should be passed in iteration 3"

That's because all of the `vars` sections are lumped together in the pre-processing step for any given role dependency (if I'm understanding correctly...) I find it odd that iteration 2 works as expected though. Perhaps it's because it's explicitly set in that particular call.

In the second role's meta/main.yml file (the role is called "meta_test_params"), which looks like this:
```
---
dependencies:
  - role: debug_test
    iteration: 1
  - role: debug_test
    iteration: 2
    passed_value: 'should be passed in iteration 2'
  - role: debug_test
    iteration: 3
    passed_value: 'should be passed in iteration 3'
  - role: debug_test
    iteration: 4
```
we get values for `passed_value` that I would normally expect:

1. expected: `undefined`, actual: `undefined`
2. expected: "should be passed in iteration 2", actual: "should be passed in iteration 2"
3. expected: "should be passed in iteration 3", actual: "should be passed in iteration 3"
4. expected: `undefined`, actual: `undefined`

I was thinking exactly the same thing you were, in regards to allowing `additionalProperties`. There's value in having things well-defined without having free-form property names that can cause confusion, so having it set to `true` makes sense to me.  It seemed like the right thing to use `vars` there, but the results indicated otherwise.

Perhaps a rule to catch when multiple `vars` blocks are defined for the same role, but in different calls would be in order.  For example, let's say there's a dependency object like this:
```
---
dependencies:
  - role: debug_test
    vars:
      variable1: value1
  - role: debug_test
    vars:
      variable2: value2
```
The new rule could warn "Ambiguous values possible: Multiple vars sections are pre-processed and applied to all calls of their respective roles"
    
[meta_tests.tar.gz](https://github.com/ansible/schemas/files/8882001/meta_tests.tar.gz)
