### ISSUE TITLE
Inconsistent schema type for "until"

### ISSUE THREAD

**Issue by fevrin** [ansible/schemas#315]
##### Summary

Using a list with "until" violates the schema, but that's contrary to Ansible 5.7.1's `ansible-doc` output.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
$ ansible --version
ansible [core 2.12.6]
  config file = /home/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /.venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /.venv/bin/ansible
  python version = 3.10.5 (main, Jun  7 2022, 19:11:36) [GCC 8.3.0]
  jinja version = 3.1.2
  libyaml = True


$ pipenv run ansible-lint --version
ansible-lint 6.3.0 using ansible 2.12.6

$ pipenv --version
pipenv, version 2021.5.29
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

Using this "until" list:
```
$ cat test.yml 
---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Succeed when output is an integer and the last digit is greater than 5
    ansible.builtin.shell: date +%s
    register: number
    retries: 5
    delay: 1
    until: number.stdout | int is integer and number.stdout | last | int > 5
  - name: debug
    ansible.builtin.debug:
      msg: >
        {{ number.stdout | last }}
        {{ number.stdout | last | type_debug }}
        {{ number.stdout | last | int }}
        {{ number.stdout | last | int | type_debug }}
  
```

Ansible-lint shows:
```
$ pipenv run ansible-lint --force-color --skip-list yaml,no-tabs --offline test.yaml 
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: test.yaml
```

Ideally, I'd be able to provide "until" with a list of those conditions instead of one string; however, as soon as I give "until" a list of even just one string, the schema fails:
```
---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Succeed when output is an integer and the last digit is greater than 5
    ansible.builtin.command: date +%s
    register: number
    retries: 5
    delay: 1
    until:
      - number.stdout | int is integer and number.stdout | last | int > 5
    changed_when: number.rc == 0
  - name: debug
    ansible.builtin.debug:
      msg: >
        {{ number.stdout | last }}
        {{ number.stdout | last | type_debug }}
        {{ number.stdout | last | int }}
        {{ number.stdout | last | int | type_debug }}

```
```
$ pipenv run ansible-lint --force-color --skip-list yaml,no-tabs --offline test.yaml
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: test.yaml
WARNING  Listing 1 violation(s) that are fatal
schema: ['number.stdout | int is integer and number.stdout | last | int > 5'] is not of type 'string' (schema[playbook])
test.yaml:1  Returned errors will not include exact line numbers, but they will mention
the schema name being used as a tag, like ``playbook-schema``,
``tasks-schema``.

This rule is not skippable and stops further processing of the file.

Schema bugs should be reported towards (https://github.com/ansible/schemas) project instead of ansible-lint.

If incorrect schema was picked, you might want to either:

* move the file to standard location, so its file is detected correctly.
* use ``kinds:`` option in linter config to help it pick correct file type.


You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - experimental  # all rules tagged as experimental

Finished with 0 failure(s), 1 warning(s) on 1 files.
```

Ansible has no issue with either version of the file, but for clarity, a list is preferable when there are multiple conditions involved, and that should be valid according to `ansible-doc`:
```
$ ansible-doc -t keyword until
until:
  applies_to:
  - Task
  description: This keyword implies a 'website for `retries` loop' that will go on until
    the condition supplied here is met or we hit the website for `retries` limit.
  priority: 0
  template: explicit
  type: list
```

##### Desired Behavior

"until" directives pass schema validation whether they contain just a single string or an array/list of strings.

##### Actual Behavior

Schema validation fails, and ansible-lint returns the above error.

##### Other info

As a test, when I updated the following lines in my local pipenv environment's version of these files with the below schema type (adapted from elsewhere in these files), ansible-lint passes.
https://github.com/ansible/schemas/blob/8e7bcf8173cce312b2dc6e0e0c8533a17aa1d0cd/f/ansible.json#L831-L834
https://github.com/ansible/schemas/blob/8e7bcf8173cce312b2dc6e0e0c8533a17aa1d0cd/f/ansible-playbook.json#L849-L852
https://github.com/ansible/schemas/blob/8e7bcf8173cce312b2dc6e0e0c8533a17aa1d0cd/f/ansible-tasks.json#L443-L446
```
"until": {                                                                                                                                                                                                                                    
  "title": "Until",
  "anyOf": [
    {
      "type": "string"
    },
    {
      "items": {
        "type": "string"
      },
      "type": "array" 
    }
  ]
},
```

However, I'm not sure if something like what "failed_when" has would be what "until" should follow:
```
"failed_when": {
  "$ref": "#/$defs/complex_conditional",
  "title": "Failed When"
},
```
