### ISSUE TITLE
Requiring ansible.builtin.import_playbook when it isn't needed

### ISSUE THREAD

**Issue by daltonv** [ansible/schemas#335]
I have a playbook that looks like this:
```yaml
---
- hosts: all
  user: pi
  become: yes

  vars:
    docker_users:
      - pi

  roles:
    - geerlingguy.docker_arm
```

The role is a role downloaded from ansible galaxy

When I run the ansible-lint on this file I get a schema error
```
schema: 'ansible.builtin.import_playbook' is a required property (schema[playbook])
```

As far as I know my playbook is perfectly valid. Is the schema wrong or am I missing something?
