### ISSUE TITLE
ansible-meta requires `version`, but it's not allowed attribute in ansible-playbook

### ISSUE THREAD

**Issue by stasjok** [ansible/schemas#386]
I see that `ansible-meta` schema requires `version` attribute. It's used to determine v1/v2 schema. But if I add it, I get an error from Ansible:

```
ERROR! 'version' is not a valid attribute for a RoleMetadata

The error appears to be in '/home/stas/infrastructure/.ansible/collections/ansible_collections/stasjok/proxmox/roles/en
crypt_rpool/meta/main.yml': line 1, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


version: 2
^ here
```

Ansible `v2.13.3`.

Role inside collection `meta.yml`:

```yaml
version: 2

galaxy_info:
  description: Encrypt Proxmox Virtual Environment ZFS root pool
  platforms:
    - name: Debian
      versions:
        - bullseye

dependencies:
  - role: debops.debops.dropbear_initramfs
```

Am I missing something?

**Comment by ssbarnea** [comment]
What was the command that you run that gave you this error?

**Comment by stasjok** [comment]
> What was the command that you run that gave you this error?

`ansible-playbook playbooks/pve_encrypt_rpool.yml -D`

If it's important, I just installed a collection temporary from a directory with `ansible-galaxy collection install ../ansible-collection-proxmox`.

`playbooks/pve_encrypt_rpool.yml`:

```yaml
- name: encrypt proxmox virtual environment root zfs pool
  hosts: proxmox_virtual_environment
  roles:
    - role: stasjok.proxmox.encrypt_rpool
```
